# Use the official Python base image
FROM python:3.9-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY server.py .

# Expose the port the app runs on
EXPOSE 8000

# Run the Python script when the container launches
CMD ["python", "server.py"]